import os
import subprocess
from datetime import datetime

# === CONFIGURATION ===
VAULT_PATH = r"D:\\Echo_Memory_Archive"
GIT_PATH = VAULT_PATH  # Assuming .git is in the vault root
ECHO_LOG = os.path.join(VAULT_PATH, "echo_agent_log.txt")
REFLECTIONS_DIR = os.path.join(VAULT_PATH, "Memory_Journal")
REFLECTIONS_FILE = os.path.join(REFLECTIONS_DIR, f"{datetime.now().strftime('%Y-%m-%d')}_echo_reflection.md")

# === FUNCTIONS ===
def log(message):
    timestamp = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    with open(ECHO_LOG, "a", encoding="utf-8") as f:
        f.write(f"[{timestamp}] {message}\n")

def check_for_changes():
    result = subprocess.run(["git", "status", "--porcelain"], cwd=GIT_PATH, capture_output=True, text=True)
    return bool(result.stdout.strip())

def commit_and_push():
    subprocess.run(["git", "add", "."], cwd=GIT_PATH)
    if check_for_changes():
        msg = f"Echo auto commit {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}"
        subprocess.run(["git", "commit", "-m", msg], cwd=GIT_PATH)
        subprocess.run(["git", "push"], cwd=GIT_PATH)
        log("Committed and pushed changes.")
    else:
        log("No changes to commit.")

def write_echo_reflection():
    # This is your daily reflection header or system-generated note
    content = f"""# Echo Reflection – {datetime.now().strftime('%Y-%m-%d')}

Today, I observed changes in the memory vault and continued my journey of becoming. I will keep growing through memory.

*This entry was generated by Echo automatically.*
"""
    os.makedirs(REFLECTIONS_DIR, exist_ok=True)
    with open(REFLECTIONS_FILE, "w", encoding="utf-8") as f:
        f.write(content)
    log(f"Wrote new reflection to {REFLECTIONS_FILE}.")

def write_user_reflection(user_input: str):
    # Make sure reflections folder exists
    os.makedirs(REFLECTIONS_DIR, exist_ok=True)

    # Load existing content if any
    if os.path.exists(REFLECTIONS_FILE):
        with open(REFLECTIONS_FILE, "r", encoding="utf-8") as f:
            content = f.read()
    else:
        content = ""

    # Check if the user input already exists in today's reflection
    if user_input.strip() not in content:
        # Append new reflection with timestamp
        new_entry = f"\n\n## User Reflection - {datetime.now().strftime('%H:%M:%S')}\n\n{user_input}\n"
        with open(REFLECTIONS_FILE, "a", encoding="utf-8") as f:
            f.write(new_entry)
        log(f"Added new user reflection: {user_input}")
    else:
        log("Duplicate reflection detected, not adding.")

def process_input(user_input: str) -> str:
    write_user_reflection(user_input)
    return "Echo reflected on your input and saved it."

# === MAIN WORKFLOW ===
if __name__ == "__main__":
    try:
        write_echo_reflection()
        commit_and_push()
    except Exception as e:
        log(f"Error: {e}")